services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - /var/lib/redis:/data
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - bmrbapi_network

  webapi:
    build:
      context: .
    image: webapi
    container_name: webapi
    ports:
      - "9005:9001"
      - "9006:9000"
    restart: always
    depends_on:
      - redis
    links:
      - redis:redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    user: "17473:10144"
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - /tmp/logs:/opt/wsgi/logs
      - /projects/BMRB/public/api/configuration.json:/opt/wsgi/bmrbapi/configuration.json
      - /projects/BMRB/depositions/timedomain_upload:/projects/BMRB/depositions/timedomain_upload
    networks:
      - bmrbapi_network

networks:
  bmrbapi_network:
    name: webapi_network
    driver: bridge
