[uwsgi]
uid = uwsgi
gid = uwsgi
wsgi-file = bmrbapi
socket = :9000
http = :9001
master = true
cheaper = 1
workers = 10
listen = 1024
buffer-size = 65535
harakiri = 300

# These ensure that long running queries (like the all-chemical shifts query) don't time out
http-timeout = 300
socket-timeout = 300
