calculate_statistics: calculate_statistics.c
	gcc -o calculate_statistics calculate_statistics.c -O3 -std=gnu99 -Wall -lm

debug: calculate_statistics.c
	gcc -o calculate_statistics calculate_statistics.c -O3 -std=gnu99 -Wall -g -lm

clean:
	rm calculate_statistics
